version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/drewbo.github.io
    steps:
      - checkout

      - run:
          name: Installing Dependencies
          command: npm install

      - run:
          name: Build the site
          command: |
             if [ "${CIRCLE_BRANCH}" == "deploy" ]; then
               node index.js
             else
               echo "Skip building site"
             fi

      - add_ssh_keys:
          fingerprints:
             - "65:57:da:1f:bd:21:94:2e:4f:ca:71:f0:f3:eb:19:c7"
      - run:
         name: Deploying to Github
         command: |
            if [ "${CIRCLE_BRANCH}" == "deploy" ]; then
               cd dist
               git init
               git config user.name "Drew Bollinger"
               git config user.email "drew@developmentseed.org"
               touch .nojekyll # Add this so GitHub doesn't try and build site
               echo "drewbo.com" > CNAME
               git add .
               git commit -m "CI deploy [skip ci]"
               git remote add origin git@github.com:drewbo/drewbo.github.io.git
               git push origin --force --quiet master
               rm -rf .git
             else
               echo "Skip deploying to Github"
            fi
